name = "stt-assembly-ner"
route = { pattern = "stt-assembly-ner.voitherbrazil.workers.dev/*", zone_name = "voitherbrazil.workers.dev" }
compatibility_date = "2024-11-01"
main = "src/index.ts"

[vars]
ENVIRONMENT = "production"
AZURE_AI_ENDPOINT = "https://voither-cognitive-brazil.cognitiveservices.azure.com"
AZURE_AI_API_VERSION = "2023-04-01"
OPENAI_API_ENDPOINT = "https://api.openai.com"
MAX_RETRIES = "3"
TIMEOUT_MS = "300000"

# Secrets configured via: wrangler secret put <SECRET_NAME>
# AZURE_AI_API_KEY
# OPENAI_API_KEY
# INTER_WORKER_TOKEN
# ADMIN_API_KEY

[[kv_namespaces]]
binding = "STT_JOBS"
id = "b8e5f5a1234567890abcdef1234567890"
preview_id = "b8e5f5a1234567890abcdef1234567891"

[[r2_buckets]]
binding = "RESULTS_STORAGE"
bucket_name = "stt-results"
preview_bucket_name = "stt-results-dev"

[env.development.vars]
ENVIRONMENT = "development"
AZURE_AI_ENDPOINT = "https://voither-cognitive-brazil-dev.cognitiveservices.azure.com"

[env.staging.vars]
ENVIRONMENT = "staging"